bind-key r source-file ~/.tmux.conf

set -g status off
set -g mouse on
set -s escape-time 0

unbind-key C-b
set-option -g prefix M-b
bind-key M-b send-prefix

bind-key -T root M-t copy-mode
# bind-key -T root M-p run "tmux set-buffer \"$(xclip -o -sel clipboard)\"; tmux paste-buffer"
bind-key -T root M-p paste-buffer
bind-key -T root M-q kill-pane

set -g mode-keys vi
set -g status-keys vi
bind-key -T copy-mode-vi v send -X begin-selection
# bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selection

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*256col*:Tc"

bind-key -T root M-h select-pane -L
bind-key -T root M-j select-pane -D
bind-key -T root M-k select-pane -U
bind-key -T root M-l select-pane -R
bind-key -T root M-v splitw -v -p 50
bind-key -T root M-n splitw -h -p 50

bind-key -T root M-r select-layout even-vertical
bind-key -T root M-e select-layout even-horizontal
