Section "OutputClass"
  Identifier "AMD GPU"
  MatchDriver "amdgpu"
  Driver "amdgpu"
  Option "DRI" "3"
  Option "TearFree" "off"
  Option "EnablePageFlip" "on"
  Option "VariableRefresh" "on"
EndSection

Section "Monitor"
  Identifier "DisplayPort-0"
  Option "Primary" "true"
  VertRefresh 160
# Modeline "3840x2160_144.00_rb2"  1306.21  3840 3848 3880 3920  2160 2300 2308 2314 +hsync -vsync
# Modeline "3840x2160_160.00_rb2"  1462.63  3840 3848 3880 3920  2160 2318 2326 2332 +hsync -vsync
# Modeline "3840x2160_160.00" 2056.78 3840 4200 4632 5424 2160 2161 2164 2370 -hsync -vsync
# Option "PreferredMode" "3840x2160_160.00"
EndSection

Section "Screen"
  Identifier "Screen"
  Device "AMD GPU"
  Monitor "DisplayPort-0"
  SubSection "Display"
  EndSubSection
EndSection
