# preload = /usr/share/pixmaps/dolomite-mountains-3840x2160-16232.png

wallpaper {
  monitor = DP-1
  path = /usr/share/pixmaps/dolomite-mountains-3840x2160-16232.png
  fit_mode = cover
}

splash = false
#fully disable ipc
# ipc = off
