#!/bin/bash

sxhkd &
polybar &
xsetroot -cursor_name left_ptr &
feh --bg-fill "${HOME}/pictures/groot-dark.png"
# lxpolkit &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width 3
bspc config window_gap 0
# bspc config split_ratio 0.5
bspc config single_monocle true
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config normal_border_color "#5e5f67"
bspc config focused_border_color "#d2d9f8" 
bspc config focus_follows_pointer true
bspc config pointer_modifier super
